services:
  db:
    image: postgres:16
    container_name: locker_finder_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: flask_app
    env_file:
      - .env
    ports:
      - "5001:5000"
    volumes:
      - .:/locker_finder
    depends_on:
      db:
        condition: service_healthy
    environment:
      - FLASK_DEBUG=1
      - POSTGRES_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - FLASK_APP=src/locker_finder/main.py

volumes:
  postgres_data: