[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "locker-finder"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "psycopg2-binary",
    "requests>=2.28",
    "python-dotenv",
    "flask>=3.1",
    "sqlmodel>=0.0.38",
    "alembic>=1.16.5"
]
